import type { Category, Product, User, Voucher, Review } from "./types";

// ================= USERS =================
export const seedUsers: User[] = [
  {
    id: "u1",
    email: "admin@shop.vn",
    password: "admin123",
    fullName: "Quản trị viên",
    role: "admin",
    createdAt: new Date().toISOString(),
    phone: "0900000001",
    address: "Hà Nội",
  },
  {
    id: "u2",
    email: "staff@shop.vn",
    password: "staff123",
    fullName: "Nhân viên A",
    role: "staff",
    createdAt: new Date().toISOString(),
    phone: "0900000002",
    address: "Hà Nội",
  },
  {
    id: "u3",
    email: "customer@shop.vn",
    password: "123456",
    fullName: "Nguyễn Văn An",
    role: "customer",
    createdAt: new Date().toISOString(),
    phone: "0912345678",
    address: "TP.HCM",
  },
];

// ================= CATEGORIES =================
export const seedCategories: Category[] = [
  { id: "c1", name: "Thời trang", slug: "thoi-trang", description: "Quần áo" },
  { id: "c2", name: "Đồ gia dụng", slug: "do-gia-dung", description: "Gia đình" },
  { id: "c3", name: "Mỹ phẩm", slug: "my-pham", description: "Làm đẹp" },
  { id: "c4", name: "Đồ ăn", slug: "do-an", description: "Thực phẩm" },
  { id: "c5", name: "Điện tử", slug: "dien-tu", description: "Thiết bị điện tử" },
  { id: "c6", name: "Thể thao", slug: "the-thao", description: "Dụng cụ thể thao" },
  { id: "c7", name: "Nội thất", slug: "noi-that", description: "Đồ dùng nội thất" },
  { id: "c8", name: "Đồ chơi", slug: "do-choi", description: "Đồ chơi trẻ em" },
  { id: "c9", name: "Sách", slug: "sach", description: "Sách và văn hóa" },
];

// ================= IMAGE FUNCTION (VISIBLE PLACEHOLDERS) =================
const img = (keyword: string) => `https://via.placeholder.com/800x600.png?text=${encodeURIComponent(keyword)}`;

// ================= PRODUCTS =================
export const seedProducts: Product[] = [
  {
    id: "p1",
    name: "Áo thun cotton premium",
    slug: "ao-thun",
    categoryId: "c1",
    price: 249000,
    oldPrice: 320000,
    stock: 48,
    image: img("tshirt,fashion"),
    description: "Áo cotton 100%, thoáng mát",
    rating: 4.6,
    createdAt: new Date().toISOString(),
  },
  {
    id: "p2",
    name: "Đầm hoa mùa hè",
    slug: "dam-hoa",
    categoryId: "c1",
    price: 459000,
    stock: 22,
    image: img("dress,fashion"),
    description: "Đầm nhẹ nhàng",
    rating: 4.8,
    createdAt: new Date().toISOString(),
  },
  {
    id: "p3",
    name: "Bộ nồi inox 5 món",
    slug: "bo-noi",
    categoryId: "c2",
    price: 1290000,
    oldPrice: 1590000,
    stock: 15,
    image: img("cookware,kitchen,pot"),
    description: "Inox 304 cao cấp",
    rating: 4.7,
    createdAt: new Date().toISOString(),
  },
  {
    id: "p4",
    name: "Máy xay sinh tố",
    slug: "may-xay",
    categoryId: "c2",
    price: 690000,
    stock: 30,
    image: img("blender,kitchen"),
    description: "Công suất mạnh",
    rating: 4.4,
    createdAt: new Date().toISOString(),
  },
  {
    id: "p5",
    name: "Serum vitamin C",
    slug: "serum",
    categoryId: "c3",
    price: 389000,
    oldPrice: 450000,
    stock: 60,
    image: img("skincare,serum"),
    description: "Sáng da",
    rating: 4.9,
    createdAt: new Date().toISOString(),
  },
  {
    id: "p6",
    name: "Son lì",
    slug: "son",
    categoryId: "c3",
    price: 219000,
    stock: 80,
    image: img("lipstick,makeup"),
    description: "Lâu trôi",
    rating: 4.5,
    createdAt: new Date().toISOString(),
  },
  {
    id: "p7",
    name: "Tai nghe Bluetooth X200",
    slug: "tai-nghe-bluetooth-x200",
    categoryId: "c5",
    price: 899000,
    stock: 42,
    image: img("headphones,electronics"),
    description: "Tai nghe không dây, chống ồn, pin 30 giờ",
    rating: 4.4,
    createdAt: new Date().toISOString(),
  },
  {
    id: "p8",
    name: "Ghế văn phòng Ergo",
    slug: "ghe-van-phong-ergo",
    categoryId: "c7",
    price: 2190000,
    stock: 12,
    image: img("chair,office,furniture"),
    description: "Ghế công thái học thoải mái",
    rating: 4.6,
    createdAt: new Date().toISOString(),
  },
  {
    id: "p9",
    name: "Bóng đá chính hãng",
    slug: "bong-da",
    categoryId: "c6",
    price: 299000,
    stock: 60,
    image: img("football,sports"),
    description: "Bóng thi đấu sân cỏ",
    rating: 4.3,
    createdAt: new Date().toISOString(),
  },
  {
    id: "p10",
    name: "Đồ chơi xếp hình 1000 mảnh",
    slug: "do-choi-xep-hinh",
    categoryId: "c8",
    price: 349000,
    stock: 48,
    image: img("puzzle,toys"),
    description: "Bộ xếp hình 1000 mảnh cho mọi lứa tuổi",
    rating: 4.7,
    createdAt: new Date().toISOString(),
  },
  {
    id: "p11",
    name: "Tiểu thuyết bán chạy",
    slug: "tieu-thuyet-ban-chay",
    categoryId: "c9",
    price: 129000,
    stock: 120,
    image: img("book,novel"),
    description: "Tiểu thuyết lôi cuốn",
    rating: 4.8,
    createdAt: new Date().toISOString(),
  },
  {
    id: "p12",
    name: "Sạc dự phòng 20000mAh",
    slug: "sac-du-phong-20000",
    categoryId: "c5",
    price: 599000,
    stock: 75,
    image: img("powerbank,electronics"),
    description: "Sạc nhanh, dung lượng lớn",
    rating: 4.5,
    createdAt: new Date().toISOString(),
  },
];

// ================= VOUCHERS =================
export const seedVouchers: Voucher[] = [
  {
    id: "v1",
    code: "WELCOME10",
    description: "Giảm 10%",
    type: "percent",
    value: 10,
    minOrder: 200000,
    expiresAt: "2026-12-31",
    active: true,
  },
];

// ================= REVIEWS =================
export const seedReviews: Review[] = [
  {
    id: "r1",
    productId: "p1",
    userId: "u3",
    userName: "Nguyễn Văn An",
    rating: 5,
    comment: "Áo đẹp!",
    createdAt: new Date().toISOString(),
  },
];